# 设置 gradle 命令使用的默认内存。可由用户或命令行属性覆盖。
# 这是为 Minecraft 反编译过程提供足够内存所必需的。
org.gradle.jvmargs=-Xmx3G -Dnet.minecraftforge.gradle.check.certs=false
org.gradle.daemon=false
org.gradle.java.home=D:\\Java\\jdk-17
org.gradle.configuration-cache=false
org.gradle.caching=false

## 环境属性

# Minecraft 版本必须与 Forge 版本一致，才能获得有效的制品
minecraft_version=1.20.1
# Minecraft 版本范围可以使用任意 Minecraft 正式发布版本作为边界。
# 快照、预发布版和候选发布版不保证能正确排序，
# 因为它们不遵循标准的版本号约定。
minecraft_version_range=[1.20.1,1.21)
# Forge 版本必须与 Minecraft 版本一致，才能获得有效的制品
forge_version=47.4.20
# Forge 版本范围可以使用任意 Forge 版本作为边界，或与加载器版本范围匹配
forge_version_range=[47,)
# 加载器版本范围只能使用 Forge/FML 的主版本作为边界
loader_version_range=[47,)
# 用于映射的映射通道。
# 默认支持的映射通道集合为 ["official", "snapshot", "snapshot_nodoc", "stable", "stable_nodoc"]。
# 可通过 Gradle 插件中的 "channelProviders" 扩展注册额外的映射通道。
#
# | 通道      | 版本                 |                                                                                |
# |-----------|----------------------|--------------------------------------------------------------------------------|
# | official  | MCVersion            | Mojang 映射文件中的官方字段/方法名                                             |
# | parchment | YYYY.MM.DD-MCVersion | 在官方映射之上叠加的开放社区来源参数名与 javadoc                               |
#
# 使用 'official' 或 'parchment' 映射时，你必须了解 Mojang 许可证。
# 更多信息见：https://github.com/MinecraftForge/MCPConfig/blob/master/Mojang.md
#
# Parchment 是由 ParchmentMC 维护的非官方项目，独立于 Minecraft Forge。
# 使用它们的映射需要额外配置，见 https://parchmentmc.org/docs/getting-started
mapping_channel=official
# 要从映射通道查询的映射版本。
# 这必须与映射通道要求的格式匹配。
mapping_version=1.20.1


## 模组属性

# 模组的唯一标识符。在英语区域设置下必须为小写。必须符合正则 [a-z][a-z0-9_]{1,63}
# 必须与标注了 @Mod 的主模组类中的 String 常量相匹配。
mod_id=trulybestfriends
# 模组的人类可读显示名称。
mod_name=Truly Best Friends Forever
# 模组的许可证。可在 https://choosealicense.com/ 查看你的选项。默认为 All Rights Reserved。
mod_license=GPL-3.0
# 模组版本。见 https://semver.org/
mod_version=0.2.4
# 模组的 group ID。仅在作为制品发布到 Maven 仓库时才重要。
# 这应与模组源码所用的基础包名相匹配。
# 见 https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=com.whidte.trulybestfriends
# 模组的作者。这是一个简单文本字符串，用于在模组列表中显示。
mod_authors=whidte
# 模组的描述。这是一个简单的多行文本字符串，用于在模组列表中显示。
mod_description=\u4e00\u4e2a\u8ba9\u5ba0\u7269\u6c38\u8fdc\u966a\u4f34\u4f60\u7684 Minecraft \u6a21\u7ec4\u3002\n\u81ea\u52a8\u8ffd\u8e2a\u9a6f\u670d\u5ba0\u7269\uff0c\u652f\u6301\u53ec\u56de\u3001\u590d\u6d3b\u3001\u8de8\u7ef4\u5ea6\u4f20\u9001\u7b49\u529f\u80fd\u3002\n\u517c\u5bb9 FTB Teams \u548c L2Tabs\u3002
